### PR TITLE
new Rook logo and mascot for v1.0

### PR DESCRIPTION
**Pull request by Chrisupbound**
Rook updates featuring logos and artwork

### CODE REVIEW

**Review by jbw976 — COMMENTED** [review]
These look to be at the root of the repo as opposed to being in a subfolder.  Is that intentional?

**Comment by Chrisupbound** [comment]
My mistake. My intention was to be able group the logos into the logo
folder and other artworks into mascot should I do it again?

**Comment by jbw976** [comment]
I'm not sure how to do this in the GitHub web UI, but i think i can clean it up using git and pushing to your branch. let me see if i can do that

**Comment by Chrisupbound** [comment]
Alright thanks, keep me posted. So what does everyone else use if not there
github UI?

**Comment by jbw976** [comment]
OK i did some git surgery locally and pushed to your remote/branch.  The commit lists you as the author, lists your email as the sign-off, and moved the files into the logo and mascot subfolders.  Please take a look @thehungryboa 

The only thing I know how to use, which you can do basically anything with, is the `git` command line client :)

**Review by Chrisupbound — COMMENTED** [review]
Looks good to me @jbw976 thanks for your help!

**Pull request merged**
